name: weather_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.2
  geolocator: ^5.3.2+2
  intl: ^0.16.1
  connectivity: ^0.4.9
  modal_progress_hud: ^0.1.3
  cached_network_image: ^2.2.0+1
  overlay_support: ^1.0.5
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  firebase_messaging: ^6.0.16
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  flutter_facebook_login: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
